# Generated by Django 5.2.15 on 2026-06-16 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0030_room_is_unscheduled_team_polls_questions"),
        ("hubspot", "0002_hubspotoauthtoken_hub_name_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectTypeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eventyay_object_type",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("order_position", "Order position"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "hubspot_object_type",
                    models.CharField(
                        choices=[("contacts", "Contacts"), ("deals", "Deals")],
                        max_length=50,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "Object Type Mapping",
                "verbose_name_plural": "Object Type Mappings",
                "ordering": ["position", "pk"],
                "unique_together": {
                    ("event", "eventyay_object_type", "hubspot_object_type")
                },
            },
        ),
    ]
