# Generated by Django 5.2.15 on 2026-06-23 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0031_migrate_meta_noindex"),
        ("hubspot", "0003_objecttypemapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubSpotProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_type", models.CharField(max_length=50)),
                ("key", models.CharField(max_length=190)),
                ("label", models.CharField(max_length=500)),
                ("data_type", models.CharField(max_length=20)),
                ("sync_batch", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "HubSpot Property",
                "verbose_name_plural": "HubSpot Properties",
                "unique_together": {("event", "object_type", "key")},
            },
        ),
        migrations.CreateModel(
            name="HubSpotPropertySyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_type", models.CharField(max_length=50)),
                ("sync_batch", models.UUIDField()),
                (
                    "next_cursor",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "HubSpot Property Sync State",
                "unique_together": {("event", "object_type")},
            },
        ),
    ]
