# Generated by Django 5.2.15 on 2026-06-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubspot", "0004_hubspotproperty_hubspotpropertysyncstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubspotfieldmapping",
            name="sync_mode",
            field=models.CharField(
                choices=[
                    ("identifier", "Identifier"),
                    ("overwrite", "Overwrite"),
                    ("fill_if_new", "Fill if new"),
                    ("fill_if_empty", "Fill if empty"),
                ],
                default="overwrite",
                max_length=20,
            ),
        ),
    ]
