name: Code Style

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - 'hubspot/locale/**'
      - 'hubspot/static/**'
  pull_request:
    branches: [ main, dev ]
    paths-ignore:
      - 'hubspot/locale/**'
      - 'hubspot/static/**'

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python 3.11
        uses: actions/setup-python@v7
        with:
          python-version: 3.11
      - uses: actions/cache@v6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install pretix
        run: pip3 install pretix
      - name: Install pre-commit
        run: pip3 install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
